---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ project_name }}
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ externalIngressAllowSourceIP|join(',') }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ project_name }}.artsy.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          serviceName: {{ project_name }}-web-internal
          servicePort: http
