FROM ruby:latest
ENV LANG C.UTF-8

ARG BUNDLE_GITHUB__COM

# Install NodeJS apt sources
RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -

RUN install_packages apt
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN install_packages nodejs yarn

# throw errors if Gemfile has been modified since Gemfile.lock
RUN bundle config --global frozen 1

# Set up deploy user and working directory
RUN adduser --disabled-password --gecos '' deploy

RUN gem install bundler

# Set up gems
WORKDIR /tmp
ADD Gemfile Gemfile
ADD Gemfile.lock Gemfile.lock
RUN bundle install -j 10 --quiet

ADD . /app
WORKDIR /app

RUN RAILS_ENV=production bundle exec rake assets:precompile

ENV PORT 8080
EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/dumb-init", "--"]
CMD ["bundle", "exec", "unicorn_rails", "-c", "./config/unicorn.rb", "--listen", "/shared/sockets/unicorn.sock"]
