---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ project_name }}-sidekiq
  namespace: default
  labels:
    app: {{ project_name }}
    component: sidekiq
    layer: application
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ project_name }}
      component: sidekiq
      layer: application
  template:
    metadata:
      labels:
        app: {{ project_name }}
        component: sidekiq
        layer: application
      name: {{ project_name }}-sidekiq
    spec:
      containers:
      - name: {{ project_name }}-sidekiq
        env:
        - name: RAILS_LOG_TO_STDOUT
          value: 'true'
        - name: MALLOC_ARENA_MAX
          value: "2"
        - name: DATADOG_TRACE_AGENT_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        envFrom:
        - configMapRef:
            name: {{ project_name }}-environment
        image: {{ project_repo }}:{{ environment }}
        imagePullPolicy: Always
        args: ["bundle", "exec", "sidekiq"]
        livenessProbe:
          exec:
            command:
            - pgrep
            - -f
            - sidekiq
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 512Mi
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      tolerations: # if ok to run on Spot instances
      - key: reserved
        operator: Equal
        value: spot
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - background
