---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: 01 15 * * MON
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            image: artsyapp-ecr-repo:versionx
            imagePullPolicy: Always
            envFrom:
            - configMapRef:
                name: environment
            args:
            - dummy
          restartPolicy: Never
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: tier
                    operator: In
                    values:
                    - background
