---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ project_name }}-sneakers
  namespace: default
  labels:
    app: {{ project_name }}
    component: sneakers
    layer: application
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ project_name }}
      component: sneakers
      layer: application
  template:
    metadata:
      labels:
        app: {{ project_name }}
        component: sneakers
        layer: application
      name: {{ project_name }}-sneakers
    spec:
      containers:
      - name: {{ project_name }}-sneakers
        env:
        - name: DATADOG_TRACE_AGENT_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: MALLOC_ARENA_MAX
          value: "2"
        envFrom:
        - configMapRef:
            name: {{ project_name }}-environment
        image: 585031190124.dkr.ecr.us-east-1.amazonaws.com/{{ project_name }}:{{ environment }}
        imagePullPolicy: Always
        args: ["bundle", "exec", "rake", "sneakers:run"]
        resources:
          requests:
            cpu: 100m
            memory: 768Mi
          limits:
            memory: 1Gi
        livenessProbe:
          exec:
            command:
            - pgrep
            - -f
            - sneakers
          initialDelaySeconds: 30
          periodSeconds: 30
        volumeMounts:
        - mountPath: /tmp
          name: tmp
      volumes:
      - name: tmp
        emptyDir: {}
      dnsPolicy: ClusterFirst
      dnsConfig:
        options:
        - name: ndots
          value: "1"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: tier
                operator: In
                values:
                - background
