---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ project_name }}-web
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ project_name }}-web
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
